//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interviewtracker.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interview
    {
        public int InterviewId { get; set; }
        public string InterviewName { get; set; }
        public string Interviewer { get; set; }
        public string InterviewUser { get; set; }
        public string UserSkills { get; set; }
        public System.DateTime InterviewDate { get; set; }
        public System.DateTime InterviewTime { get; set; }
        public int InterViewsStatus { get; set; }
        public int TInterViews { get; set; }
        public string Remark { get; set; }
        public Nullable<int> ApplicationUsersUserId { get; set; }
    
        public virtual ApplicationUser ApplicationUser { get; set; }
    }
}
